#
#	Global configuration for SNAP makefiles
#

GLIB = glib-core
SNAP = snap-core
GLIBADV = glib-adv
SNAPADV = snap-adv
SNAPEXP = snap-exp

CGLIB = ../$(GLIB)
CSNAP = ../$(SNAP)

EXGLIB = ../../$(GLIB)
EXSNAP = ../../$(SNAP)
EXGLIBADV = ../../$(GLIBADV)
EXSNAPADV = ../../$(SNAPADV)
EXSNAPEXP = ../../$(SNAPEXP)

# UNAME := $(shell uname)
UNAME := MINGW

ifeq ($(UNAME), MINGW)
  # MinGW flags for Windows
  CC = gcc
  CXX = g++
  CXXFLAGS = -std=c++98 -Wall -O3 -DNDEBUG
  CXXOPENMP =
  LDFLAGS =
  LIBS =
endif

ifeq ($(UNAME), Linux)
  # Linux flags
  CC = g++
  CXXFLAGS += -std=c++98 -Wall
  CXXFLAGS += -O3 -DNDEBUG
  # turn on for crash debugging, get symbols with <prog> 2>&1 | c++filt
  #CXXFLAGS += -g -rdynamic
  CXXOPENMP = -fopenmp
  LDFLAGS +=
  LIBS += -lrt

else ifeq ($(UNAME), Darwin)
  # OS X flags
  CC = g++
  CXXFLAGS += -std=c++98 -Wall
  CXXFLAGS += -O3 -DNDEBUG
  CXXOPENMP = -fopenmp
  CLANG := $(shell g++ -v 2>&1 | grep clang | cut -d " " -f 2)
  ifeq ($(CLANG), LLVM)
    CXXOPENMP =
    CXXFLAGS += -DNOMP
  endif

  LDFLAGS +=
  LIBS +=

endif

